language: node_js
node_js:
- node
- '10'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  tag: next
  email: $NPM_EMAIL
  api_key:
    secure: $NPM_API_KEY_SECURE
  on:
    branch: master