language: node_js
node_js:
- node
- '10'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  on:
    branch: master
  api_key:
    secure: unRQMI4NB6n71NTjJuyuzVzjtIARZAXxoRvjR83yzlXx/J09TztkB9TIYODs9xv0cJIhIsCjFLKLIkUHI967EjPzAHLPA0zkHIRU2uLTT7rhndUvYhXH7fBQjOfqohQOCtBUkORy7ucuHsxULz6RQot6RhQhUUhT1hoAPQ6GWSEWrWZcaG0M3jeAGcJwT4VUZ7nu6Osf3h8lqQl+P9bDkCbDhfdwbttPvHyvSk0OoEqFy/WE0WKJ291aiBdcGUF1eHu821MYzhN0hg+So9ONAkCUBGr8ukeQLYMG1FLILzJTuVTPfeuEIRH4zsTQQb5PlM4jjwUHZHGCUvYsWzASxNGGulHNC7OtB7jExMCRJZdzLpJdkvNawPAa0+qfphJTEaPD0mNLxq/oDO6Q190IruVg0gdtmcgU4jfzvnBnf57dp/fJ0TlTEnkz9DRGBT3htv9L5Cng8Q2xrO9hgO2rKXk0j0k/nsxnwRS6mjhv/WAkpIXFXWyWejdEaRn9CRjYfC6V3prA1i8JMzxmh0f5bG5C32kuTXffPAG4E1jo4eIg4OLPc3TOF0bTBuanUcgEo+d3f3NYszXpAJa/5vHNSxjZJXGjrIrDPQdoWtyYSPM+jx20pYK56mcLuYw8oYBLMHCbZLRYHrTWL60D1G22DN9ocsBfiq7t32C7FRoVwI0=
  email:
    secure: Z9MIcsgL5noofY9sPSduOfAc7vWGj7PlMzSodwsyAvT1Wcw86/giWJd9YUnVX0DjvcT9Jwbb1Ho0kwkM8o5c4u6BKOD0kU5rHyf0/djE92Tg43/KWzKY7ht+zXr+pEAYXNkUrh2DLD3c6V89zjY4tKD7Az946pRekocymDl2rbZMZLYo8icP49GQgnhJPZ4IIudg+kK29jVv1sTuQqTtvkSqpKUJKhu7uB9OslhrHefoT9OmnsOJmTQeBhX9f7mCZGKJ8OdOp8gaz1YXdczSFPKzDwUpmxBiFoHV4JGoZwW8tkDybYyf2Zgvkzk812VLubPI7fweHmk6iO2zgaFJbVMaHKNFWJXi0oGXOK4fDbRsC76JgjCy1v4sUtjq1cVCsdxH63Cz8+oBlB8VMWgxN951DceaeaMK+qERsO6Nir0lSmWgkyzyi2zWRfXnUr9+xZlLHbgZ2vH5Ar0SRtsH8jGTJ/kw2WVJrAhNntWI+zIvdfaJaHE9JO1dCxnWsRbpnoUds/hMjV3tI+TpCyLLOK+MEF9YFHWPLD6MO346E5UW+d5aDe2tK1ldZKO2FPwcrKmk3C1yJ6k4+3YVT2ZeQqbaXul2VMDXvm7bzuJJnW3kMqNkV/cSzKT42mYWmAlD9ob/bJhTGVRK0BDTPVutEmM/cGNfRuvken49fC2EPhg=
