## mock configs for the serverless initialization
service: announcer-test

custom: ${file(./test/customSlsConfig.js):configurations.custom}

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 256 
  timeout: 200
  region: eu-central-1

functions:
  sharpness:
    announcer-test: mock.handler.js
    events: 
      - http:
          path: mock
          method: put
          cors: true

package:
  exclude:
    - venv/**
    - .vscode/**
    - node_modules/**