##
# mock configs for the serverless initialization
# used for testing purposes
##

service: announcer-test

custom: ${file(./test/mock/config.js)}

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 256 
  timeout: 200
  region: eu-central-1

functions:
  announcer-test:
    handler: test/mock/handler.yo
    events: 
      - http:
          path: mock
          method: put
          cors: true
  dido:
    handler: test/mock/handler.yo
    events: 
      - http:
          path: mock/dido
          method: put
          cors: true

package:
  exclude:
    - venv/**
    - .vscode/**
    - node_modules/**